# Generated by Django 2.0.7 on 2018-09-04 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('cat_id', models.CharField(max_length=4)),
                ('category', models.CharField(choices=[('vehicle_house', '车房'), ('other', '其他'), ('digital', '数码产品'), ('instrument_toy', '乐器玩具'), ('book', '图书'), ('clothing', '服鞋包配饰'), ('toll', '配件设备工具')], max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cat',
            },
        ),
        migrations.CreateModel(
            name='L_cat',
            fields=[
                ('large_id', models.CharField(max_length=4)),
                ('large_category', models.CharField(choices=[('租', '租'), ('卖', '卖'), ('送', '送')], max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'l_cat',
            },
        ),
        migrations.CreateModel(
            name='Goods_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('phone', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=100)),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('category', models.ForeignKey(default='other', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goods.Cat')),
            ],
            options={
                'db_table': 'goods_detail',
            },
        ),
        migrations.AddField(
            model_name='goods_detail',
            name='large_category',
            field=models.ForeignKey(default='租', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='goods.L_cat'),
        ),
    ]
