# Generated by Django 2.0.7 on 2018-09-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('book', '图书'), ('toll', '配件设备工具'), ('vehicle_house', '车房'), ('other', '其他'), ('digital', '数码产品'), ('clothing', '服鞋包配饰'), ('instrument_toy', '乐器玩具')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='category',
            field=models.ForeignKey(default='c01', max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goods.Cat'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='large_category',
            field=models.ForeignKey(default='b01', max_length=10, on_delete=django.db.models.deletion.CASCADE, to='goods.L_cat'),
        ),
        migrations.AlterField(
            model_name='l_cat',
            name='large_category',
            field=models.CharField(choices=[('租', '租'), ('卖', '卖'), ('送', '送')], max_length=10),
        ),
        migrations.AlterField(
            model_name='l_cat',
            name='large_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
