# Generated by Django 2.0.7 on 2018-09-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180904_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='category',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goods.Cat'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='large_category',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='goods.L_cat'),
        ),
        migrations.AlterField(
            model_name='l_cat',
            name='large_category',
            field=models.CharField(max_length=10),
        ),
    ]
