# Generated by Django 2.0.7 on 2018-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180904_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('other', '其他'), ('instrument_toy', '乐器玩具'), ('book', '图书'), ('clothing', '服鞋包配饰'), ('vehicle_house', '车房'), ('digital', '数码产品'), ('toll', '配件设备工具')], max_length=20),
        ),
        migrations.AlterField(
            model_name='l_cat',
            name='large_category',
            field=models.CharField(choices=[('租', '租'), ('卖', '卖'), ('送', '送')], max_length=10),
        ),
    ]
