# Generated by Django 2.0.7 on 2018-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180904_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('instrument_toy', '乐器玩具'), ('clothing', '服鞋包配饰'), ('toll', '配件设备工具'), ('book', '图书'), ('other', '其他'), ('digital', '数码产品'), ('vehicle_house', '车房')], max_length=20),
        ),
    ]
