# Generated by Django 2.0.7 on 2018-09-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180904_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('instrument_toy', '乐器玩具'), ('other', '其他'), ('book', '图书'), ('clothing', '服鞋包配饰'), ('toll', '配件设备工具'), ('digital', '数码产品'), ('vehicle_house', '车房')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='category',
            field=models.CharField(choices=[('c02', '图书'), ('c0', '其他'), ('c06', '车房'), ('c05', '配件设备工具'), ('c03', '服鞋包配饰'), ('c01', '数码产品'), ('c04', '乐器玩具')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='large_category',
            field=models.CharField(choices=[('b01', '租'), ('b02', '卖'), ('b03', '送')], max_length=10),
        ),
    ]
