# Generated by Django 2.0.7 on 2018-09-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180905_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('vehicle_house', '车房'), ('other', '其他'), ('book', '图书'), ('clothing', '服鞋包配饰'), ('toll', '配件设备工具'), ('instrument_toy', '乐器玩具'), ('digital', '数码产品')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='category',
            field=models.CharField(choices=[('c03', '服鞋包配饰'), ('c05', '配件设备工具'), ('c06', '车房'), ('c04', '乐器玩具'), ('c0', '其他'), ('c01', '数码产品'), ('c02', '图书')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_1',
            field=models.ImageField(default='C:/Users/acer/Pictures/001.jpg', upload_to='img_upload'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_2',
            field=models.ImageField(default='C:/Users/acer/Pictures/001.jpg', upload_to='img_upload'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_3',
            field=models.ImageField(default='C:/Users/acer/Pictures/001.jpg', upload_to='img_upload'),
        ),
    ]
