# Generated by Django 2.0.7 on 2018-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20180905_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('instrument_toy', '乐器玩具'), ('other', '其他'), ('clothing', '服鞋包配饰'), ('vehicle_house', '车房'), ('book', '图书'), ('digital', '数码产品'), ('toll', '配件设备工具')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='category',
            field=models.CharField(choices=[('c02', '图书'), ('c0', '其他'), ('c05', '配件设备工具'), ('c06', '车房'), ('c01', '数码产品'), ('c04', '乐器玩具'), ('c03', '服鞋包配饰')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_1',
            field=models.ImageField(default='C:/Users/acer/Pictures/001.jpg', upload_to='img_upload'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_2',
            field=models.ImageField(default='C:/Users/acer/Pictures/001.jpg', upload_to='img_upload'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_3',
            field=models.ImageField(default='C:/Users/acer/Pictures/001.jpg', upload_to='img_upload'),
        ),
    ]
