# Generated by Django 2.0.7 on 2018-09-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20180906_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.CharField(choices=[('book', '图书'), ('instrument_toy', '乐器玩具'), ('toll', '配件设备工具'), ('clothing', '服鞋包配饰'), ('other', '其他'), ('digital', '数码产品'), ('vehicle_house', '车房')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='category',
            field=models.CharField(choices=[('c06', '车房'), ('c04', '乐器玩具'), ('c02', '图书'), ('c03', '服鞋包配饰'), ('c01', '数码产品'), ('c0', '其他'), ('c05', '配件设备工具')], max_length=20),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_1',
            field=models.ImageField(default='img_upload/001.png', upload_to='img_upload'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_2',
            field=models.ImageField(default='img_upload/001.png', upload_to='img_upload'),
        ),
        migrations.AlterField(
            model_name='goods_detail',
            name='img_3',
            field=models.ImageField(default='img_upload/001.png', upload_to='img_upload'),
        ),
    ]
